version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    